### ISSUE TITLE
Event cumulate

### ISSUE THREAD

**Issue by Briareos12** [staskobzar/amiws_queue#3]
hello sir, 

I've a problem with the wallboard. 
In fact, when there is many vue's instances, the data is cumulate. 
For esample for total agent, if the value is 20 and if somebody open the instance, the value will change to 40. 
Have you an idea to resolve this problem ? 
Thanks in advance;

**Comment by staskobzar** [comment]
Hello,
Sorry for delay. Actually, I am currently not using this project in production so I do not quite remember the details. But there supposed to be only one Vue instance. Root Vue instance.
Can you provide more details, may be with step-by-step instructions on how to reproduce the bug, please?
Thanks

**Comment by Briareos12** [comment]
Hello,
Thanks for your response.
To reproduce the bug you just need to open the website many time. « n - 1 » instance will addition the data from  the instance « n »
So if you look the component topstat the value will change in function of the instance number.
I think its a problem with the store cache or juste the way to read event from asterisk...
Thanks a lot

**Comment by staskobzar** [comment]
Do you mean, open in new browser tab?

**Comment by Briareos12** [comment]
Yes, its exactly that

**Comment by staskobzar** [comment]
Ok, I see. I will be back when I find a solution. Thanks.

**Comment by Briareos12** [comment]
Thanks a lot, I believe in you 🙏
After that I will share with you, a new   wallboard interface with agent in calls and callers in wait  :)

**Comment by staskobzar** [comment]
Hello,
The issue should be fixed now. I was able to reproduce it in Asterisk ver 12+ which has a lot of changes in AMI. Please, confirm it works for you.
Also, keep in mind that this project is just an example on how to use another project [amiws](https://github.com/staskobzar/amiws).

**Comment by Briareos12** [comment]
It's works ! Perfect ! Thanks a lot 🥇
