### ISSUE TITLE
eventwhencalled and eventmemberstatus removed in Asterisk 12

### ISSUE THREAD

**Issue by bestann** [staskobzar/amiws_queue#4]
"The configuration options eventwhencalled and eventmemberstatus have been removed. As a result, the AMI events QueueMemberStatus, AgentCalled, AgentConnect, AgentComplete, AgentDump, and AgentRingNoAnswer will always be sent. The Variable fields will also no longer exist on the Agent* events. These events can be filtered out from a connected AMI client using the eventfilter setting in manager.conf."  Does amiws_queue work in Asterisk 15 and 16?

**Comment by staskobzar** [comment]
I did not test it with Asterisk 15 and 16. But since it works in 13 it should work with 15 and 16.
