### ISSUE TITLE
Invalid/Unknown command

### ISSUE THREAD

**Issue by bestann** [staskobzar/amiws_queue#6]
I've installed amiws and amiws_queue.
Open http://ip-address:8000
Asterisk 15.6.1. What should I check?
All queues are shown, but a red window appears for serveral seconds:

> Invalid/unknown command: Queues. Use Action: ListCommands to show available commands.

**Comment by staskobzar** [comment]
apparently, some AMI command is not compatible. You can sniff AMI tcp connection to see which action is not accepted. Or you can debug with Asterisk to see if there are more info in asterisk logs.

**Comment by bestann** [comment]
I've checked documentation. There was Queue action in Asterisk13 and no such action in Asterisk 15.
Can I change this command to QueueStatus? What filw should I change?

Asterisk 15:
```
QueueAdd                     Add interface to queue. 
QueueChangePriorityCaller    Change priority of a caller on qu
QueueLog                     Adds custom entry in queue_log. 
QueueMemberRingInUse         Set the ringinuse value for a que
QueuePause                   Makes a queue member temporarily 
QueuePenalty                 Set the penalty for a queue membe
QueueReload                  Reload a queue, queues, or any su
QueueRemove                  Remove interface from queue. 
QueueReset                   Reset queue statistics. 
QueueRule                    Queue Rules. 
QueueStatus                  Show queue status. 
QueueSummary                 Show queue summary. 
```

https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+AMI+Actions
```
QueueAdd
QueueLog
QueueMemberRingInUse
QueuePause
QueuePenalty
QueueReload
QueueRemove
QueueReset
QueueRule
Queues !!!
QueueStatus
QueueSummary 
```

**Comment by staskobzar** [comment]
web socket is sending command on connection:
https://github.com/staskobzar/amiws_queue/blob/master/src/websock/index.js

Probably it will take to update also Vue store mutations on message received.
